export const surprise = [
  "Imagine a world where everything is made of candy.",
  "What would a city look like if it was built entirely out of ice?",
  "Create an underwater kingdom filled with mythical creatures.",
  "A sky full of hot air balloons in every color of the rainbow.",
  "An enchanted forest filled with talking animals and magical creatures.",
  "A futuristic city floating in the clouds.",
  "A desert island filled with buried treasure and pirates.",
  "A world where animals have superpowers.",
  "A post-apocalyptic wasteland filled with mutated creatures.",
  "A castle floating in the clouds surrounded by dragons.",
  "An ancient temple hidden deep within the jungle.",
  "A vibrant and bustling market in the heart of a bustling met",
  "An underwater world with mermaids and sea creatures",
  "A floating city built on clouds",
  "A robot city filled with advanced technology",
  "A world inhabited by miniature people",
  "A village with talking plants and trees",
  "An abandoned theme park filled with ghosts",
  "A sky full of flying cars and airships",
  "A planet with two suns and multiple moons",
  "An enchanted garden with hidden fairies",
  "A city surrounded by a massive wall of fire",
  "A world where time moves backwards.",
  "An island full of bananas who think they are humans",
  "A world where dogs wear hats and have their own cafes",
  "A city where all the buildings are shaped like giant mushrooms",
  "An amusement park with giant hamster wheels and cheese slide",
  "A village where all the residents are chickens",
  "A world where everything is made of jelly",
  "A park filled with oversized insects",
  "A city with buildings made entirely of cheese",
  "An underwater world with fish who are detectives",
  "A world where everything is upside down.",
  "A planet with multiple ecosystems each with its own unique creatures",
  "An alternate universe where everyone has a superpower",
  "A world where humans live in symbiosis with giant space creatures",
  "A city that floats above the clouds powered by advanced technology",
  "An underwater world filled with ancient ruins and mysterious artifacts",
  "A world where humans and mythical creatures coexist and work together",
  "A city made entirely of crystal and light shining brightly in the dark",
  "A world where time travel is possible and people can visit the past and future",
  "A kingdom of floating islands each with its own unique culture and traditions",
  "A world where death doesn't exist and people live forever.",
  "An ancient civilization with advanced technology",
  "A world of legendary heroes and mythical creatures",
  "A world where mythical gods interact with humans",
  "A medieval world with mythical creatures like dragons and unicorns",
  "A world where magic and science coexist and are used in harmony",
  "An alternate universe where the Roman Empire never fell.",
  "A medieval kingdom with knights and castles",
  "A world where alchemy is a common and powerful practice",
  "A pirate-filled world of sea adventures and treasure hunting",
  "A world where magic is used in everyday life and mythical creatures exist.",
];
